# -*- coding: utf-8 -*-
"""자리

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOjFz5C_h34QlwiUNUtNe_6x2QqtMWw-
"""

!pip -q install flask pyngrok

from flask import Flask, render_template_string, redirect
import random, json, os, copy
from datetime import datetime, timedelta

app = Flask(__name__)

# ================= TIME =================
def now_ict():
    return datetime.utcnow() + timedelta(hours=7)

def format_time():
    dt = now_ict()
    days = ["월","화","수","목","금","토","일"]
    return dt.strftime(f"%Y-%m-%d %H:%M ({days[dt.weekday()]})")

# ================= STUDENTS =================
students = [
"김건구","김대권","김동우","김선준","김세아","김주영","김지윤",
"문예은","민다니엘","민지현","박윤아","박휘준","배유나",
"신범철","신온유","어수민","오시온","오은우","우상우",
"이연아","이재헌","이지영","정구윤","정선우","정연미",
"정원준","조건우","주준하","차정호","최지수","편윤아",
"한규란","한려원","손정인","안지유"
]

# ================= SEATS =================
seat_layout = [
["A1","A2","B1","B2","C1","C2"],
["A3","A4","B3","B4","C3","C4"],
["A5","A6","B5","B6","C5","C6"],
["D1","D2","E1","E2","F1","F2"],
["D3","D4","E3","E4","F3","F4"],
["D5","D6","E5","E6","F5"],
]

FILE = "data.json"

# ================= LOAD / SAVE =================
def load():
    if os.path.exists(FILE):
        return json.load(open(FILE, encoding="utf-8"))
    return {"saved": [], "current": None}

def save(data):
    json.dump(
        data,
        open(FILE, "w", encoding="utf-8"),
        ensure_ascii=False,
        indent=2
    )

data = load()

saved = data["saved"]

if data["current"]:
    seats = data["current"]
else:
    seats = [
        [{"name":"", "fixed":False} for _ in row]
        for row in seat_layout
    ]

def persist():
    save({
        "saved": saved,
        "current": seats
    })

# ================= RANDOM ASSIGN =================
def assign():

    empty_positions = []
    fixed_students = []

    for r in range(len(seats)):
        for c in range(len(seats[r])):

            if seats[r][c]["fixed"]:
                fixed_students.append(
                    seats[r][c]["name"]
                )
            else:
                empty_positions.append((r,c))

    free_students = [
        s for s in students
        if s not in fixed_students
    ]

    random.shuffle(free_students)

    for i, (r,c) in enumerate(empty_positions):
        seats[r][c]["name"] = free_students[i]

# ================= ROUTES =================
@app.route("/")
def home():

    return render_template_string(
        HTML,
        seats=seats,
        saved=saved
    )

@app.route("/assign")
def random_assign():

    assign()
    persist()

    return redirect("/")

@app.route("/swap/<int:r1>/<int:c1>/<int:r2>/<int:c2>")
def swap(r1,c1,r2,c2):

    if seats[r1][c1]["fixed"] or seats[r2][c2]["fixed"]:
        return "locked"

    seats[r1][c1]["name"], seats[r2][c2]["name"] = \
    seats[r2][c2]["name"], seats[r1][c1]["name"]

    persist()

    return "ok"

@app.route("/fix/<int:r>/<int:c>")
def fix(r,c):

    seats[r][c]["fixed"] = not seats[r][c]["fixed"]

    persist()

    return "ok"

@app.route("/save")
def save_route():

    # 최대 4개 -> 5번째 저장 시 전체 초기화
    if len(saved) >= 4:
        saved.clear()

    saved.append({
        "time": format_time(),
        "seats": copy.deepcopy([
            [s["name"] for s in row]
            for row in seats
        ])
    })

    persist()

    return redirect("/")

@app.route("/load/<int:i>")
def load_route(i):

    layout = saved[i]["seats"]

    for r in range(len(seats)):
        for c in range(len(seats[r])):

            seats[r][c]["name"] = layout[r][c]

    persist()

    return redirect("/")

@app.route("/delete/<int:i>")
def delete_route(i):

    saved.pop(i)

    persist()

    return redirect("/")

# ================= HTML =================
HTML = """
<!doctype html>
<html>
<head>
<meta charset="utf-8">

<style>

body{
    font-family:Arial;
    background:linear-gradient(135deg,#1f1c2c,#928dab);
    text-align:center;
    color:white;
}

h2{
    margin-top:20px;
}

.panel{
    background:rgba(255,255,255,0.15);
    padding:15px;
    margin:20px auto;
    width:90%;
    border-radius:20px;
    backdrop-filter:blur(10px);
}

button{
    padding:10px 15px;
    border:none;
    border-radius:12px;
    font-weight:bold;
    cursor:pointer;
    margin:5px;
}

table{
    margin:auto;
    border-spacing:10px;
}

td{
    width:90px;
    height:60px;
    background:white;
    color:black;
    border-radius:15px;
    font-weight:bold;
    cursor:grab;
    user-select:none;
    transition:0.2s;
}

td:hover{
    transform:scale(1.05);
}

.fixed{
    background:#ffd54f !important;
}

.card{
    background:white;
    color:black;
    margin:10px;
    padding:10px;
    border-radius:15px;
}

a{
    text-decoration:none;
    font-weight:bold;
}

</style>
</head>

<body>

<h2>🪑 자리배치 앱 FINAL</h2>

<div class="panel">

<a href="/assign">
<button>🎲 랜덤</button>
</a>

<a href="/save">
<button>💾 저장</button>
</a>

<p>
🟨 한 번 클릭 = 고정
</p>

<p>
🖱 드래그 = 자리 교환
</p>

</div>

<table>

{% for r in range(seats|length) %}
<tr>

{% for c in range(seats[r]|length) %}

<td
draggable="true"
ondragstart="drag(event)"
ondrop="drop(event)"
ondragover="allow(event)"
onclick="fix({{r}},{{c}})"
data-r="{{r}}"
data-c="{{c}}"
class="{% if seats[r][c].fixed %}fixed{% endif %}"
>

{{seats[r][c].name}}

</td>

{% endfor %}

</tr>
{% endfor %}

</table>

<div class="panel">

<h3>📜 저장 기록 (최대 4개)</h3>

{% for s in saved %}

<div class="card">

<b>{{s.time}}</b>

<br><br>

<a href="/load/{{loop.index0}}">
불러오기
</a>

｜

<a href="/delete/{{loop.index0}}">
삭제
</a>

<br><br>

<table>

{% for row in s.seats %}
<tr>

{% for name in row %}

<td style="width:50px;height:30px;">
{{name}}
</td>

{% endfor %}

</tr>
{% endfor %}

</table>

</div>

{% endfor %}

</div>

<script>

let from = null;

function drag(e){

    from = e.target;

}

function allow(e){

    e.preventDefault();

}

function drop(e){

    e.preventDefault();

    let to = e.target;

    fetch(`/swap/${from.dataset.r}/${from.dataset.c}/${to.dataset.r}/${to.dataset.c}`)
    .then(()=>location.reload());

}

function fix(r,c){

    fetch(`/fix/${r}/${c}`)
    .then(()=>location.reload());

}

</script>

</body>
</html>
"""

# ================= RUN =================
if __name__ == "__main__":

    port = int(os.environ.get("PORT", 5000))

    app.run(
        host="0.0.0.0",
        port=port
    )